/**
 * Quantum Research Lab (QRL) - 23 Verified Benchmark Experiments
 * Verified baseline suite from QRL-001 through QRL-023.
 * Includes complete circuit definitions, Dirac notation formulas, Qiskit & PennyLane implementations.
 */

import { BenchmarkExperiment } from '../../types/quantum';
import { exportToPennyLane, exportToQiskit } from './qasm';

export const VERIFIED_EXPERIMENTS: BenchmarkExperiment[] = [
  {
    id: 'exp-001',
    code: 'QRL-001',
    name: 'Single-Qubit Superposition',
    category: 'Single-Qubit',
    numQubits: 1,
    circuitDepth: 1,
    gateCount: 1,
    cnotCount: 0,
    referenceFidelity: 0.9998,
    verifiedBaseline: true,
    historicalMeasurement: {
      shots: 1024,
      outcome0: 532,
      outcome1: 492,
      frequency0: 0.5195,
      frequency1: 0.4805,
      label: 'Verified Historical Benchmark Run #1042-B (1,024 Shots)',
    },
    description: 'Fundamental demonstration of quantum superposition by applying a Hadamard gate to computational basis state |0⟩.',
    learningObjectives: [
      'Understand the transition from classical discrete bit to quantum continuous state.',
      'Analyze the transformation |0⟩ → (|0⟩ + |1⟩)/√2.',
      'Observe 50/50 probability distribution in measurement collapse.',
    ],
    theoreticalBehavior: 'Equal probability P(|0⟩) = 0.5 and P(|1⟩) = 0.5. Bloch vector points to (+1, 0, 0) on the X-axis.',
    matrixFormula: 'H = \\frac{1}{\\sqrt{2}}\\begin{pmatrix} 1 & 1 \\\\ 1 & -1 \\end{pmatrix}',
    circuit: {
      id: 'circ-qrl-001',
      name: 'QRL-001 Single-Qubit Superposition',
      description: 'Hadamard transformation on |0⟩',
      numQubits: 1,
      timeSteps: 4,
      gates: [
        { id: 'g1', type: 'H', step: 0, targetQubit: 0 },
        { id: 'g2', type: 'M', step: 1, targetQubit: 0 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-002',
    code: 'QRL-002',
    name: 'Pauli-X Deterministic Bit Flip',
    category: 'Single-Qubit',
    numQubits: 1,
    circuitDepth: 1,
    gateCount: 1,
    cnotCount: 0,
    referenceFidelity: 0.9999,
    verifiedBaseline: true,
    description: 'Classical NOT analogue: rotates the statevector by π radians around the X-axis on the Bloch sphere.',
    learningObjectives: [
      'Verify deterministic state transition |0⟩ → |1⟩.',
      'Confirm probability P(|1⟩) = 1.0 with 0% measurement error in ideal simulation.',
      'Bloch sphere pole transition: North pole (0, 0, 1) to South pole (0, 0, -1).',
    ],
    theoreticalBehavior: 'P(|0⟩) = 0.0, P(|1⟩) = 1.0. Bloch vector: (0, 0, -1).',
    matrixFormula: 'X = \\begin{pmatrix} 0 & 1 \\\\ 1 & 0 \\end{pmatrix}',
    circuit: {
      id: 'circ-qrl-002',
      name: 'QRL-002 Pauli-X Bit Flip',
      description: 'X gate rotation on |0⟩',
      numQubits: 1,
      timeSteps: 4,
      gates: [
        { id: 'g1', type: 'X', step: 0, targetQubit: 0 },
        { id: 'g2', type: 'M', step: 1, targetQubit: 0 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-003',
    code: 'QRL-003',
    name: 'Pauli-Y Bit & Phase Rotation',
    category: 'Single-Qubit',
    numQubits: 1,
    circuitDepth: 1,
    gateCount: 1,
    cnotCount: 0,
    referenceFidelity: 0.9997,
    verifiedBaseline: true,
    description: 'Rotates statevector by π radians around the Y-axis, introducing an imaginary phase unit i.',
    learningObjectives: [
      'Examine imaginary amplitude component: Y|0⟩ = i|1⟩.',
      'Observe probability P(|1⟩) = 1.0 with phase arg(c) = +π/2.',
    ],
    theoreticalBehavior: 'Amplitude |0⟩: 0; Amplitude |1⟩: i. Probabilities P(|0⟩)=0, P(|1⟩)=1.',
    matrixFormula: 'Y = \\begin{pmatrix} 0 & -i \\\\ i & 0 \\end{pmatrix}',
    circuit: {
      id: 'circ-qrl-003',
      name: 'QRL-003 Pauli-Y Bit & Phase Rotation',
      description: 'Y gate on |0⟩',
      numQubits: 1,
      timeSteps: 4,
      gates: [
        { id: 'g1', type: 'Y', step: 0, targetQubit: 0 },
        { id: 'g2', type: 'M', step: 1, targetQubit: 0 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-004',
    code: 'QRL-004',
    name: 'Pauli-Z Phase Flip in Superposition',
    category: 'Single-Qubit',
    numQubits: 1,
    circuitDepth: 3,
    gateCount: 3,
    cnotCount: 0,
    referenceFidelity: 0.9995,
    verifiedBaseline: true,
    description: 'Demonstrates phase flip by transforming |+⟩ = (|0⟩+|1⟩)/√2 into |-⟩ = (|0⟩-|1⟩)/√2, then testing with an interferometric basis rotation.',
    learningObjectives: [
      'Distinguish phase differences that do not immediately alter computational basis probabilities.',
      'Use an interfering Hadamard gate to map relative phase back into measurable population.',
    ],
    theoreticalBehavior: 'H-Z-H produces deterministic outcome |1⟩ with P(|1⟩) = 1.0.',
    matrixFormula: 'Z = \\begin{pmatrix} 1 & 0 \\\\ 0 & -1 \\end{pmatrix}',
    circuit: {
      id: 'circ-qrl-004',
      name: 'QRL-004 Pauli-Z Phase Flip',
      description: 'H-Z-H interferometric sequence',
      numQubits: 1,
      timeSteps: 5,
      gates: [
        { id: 'g1', type: 'H', step: 0, targetQubit: 0 },
        { id: 'g2', type: 'Z', step: 1, targetQubit: 0 },
        { id: 'g3', type: 'H', step: 2, targetQubit: 0 },
        { id: 'g4', type: 'M', step: 3, targetQubit: 0 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-005',
    code: 'QRL-005',
    name: 'S Gate Quarter-Turn Phase Shift',
    category: 'Phase & Rotation',
    numQubits: 1,
    circuitDepth: 2,
    gateCount: 2,
    cnotCount: 0,
    referenceFidelity: 0.9996,
    verifiedBaseline: true,
    description: 'Applies π/2 phase rotation along the Z-axis, creating state (|0⟩ + i|1⟩)/√2 (the |+i⟩ eigenstate of Pauli-Y).',
    learningObjectives: [
      'Understand the S gate as the square root of Z: S² = Z.',
      'Inspect the Bloch vector pointing along the +Y axis (0, 1, 0).',
    ],
    theoreticalBehavior: 'Amplitudes: c0 = 1/√2, c1 = i/√2. Bloch vector: (0, 1, 0).',
    matrixFormula: 'S = \\begin{pmatrix} 1 & 0 \\\\ 0 & i \\end{pmatrix}',
    circuit: {
      id: 'circ-qrl-005',
      name: 'QRL-005 S Gate Phase Shift',
      description: 'H followed by S gate',
      numQubits: 1,
      timeSteps: 4,
      gates: [
        { id: 'g1', type: 'H', step: 0, targetQubit: 0 },
        { id: 'g2', type: 'S', step: 1, targetQubit: 0 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-006',
    code: 'QRL-006',
    name: 'T Gate (π/8 Non-Clifford Gate)',
    category: 'Phase & Rotation',
    numQubits: 1,
    circuitDepth: 2,
    gateCount: 2,
    cnotCount: 0,
    referenceFidelity: 0.9994,
    verifiedBaseline: true,
    description: 'Crucial gate for universal fault-tolerant quantum computation: applies an eighth-turn phase shift e^(iπ/4).',
    learningObjectives: [
      'Explain why Clifford gates alone (H, S, CNOT) are efficiently simulable classically (Gottesman-Knill theorem).',
      'Verify how T provides universal quantum expressivity.',
    ],
    theoreticalBehavior: 'State (|0⟩ + e^{i\\pi/4}|1⟩)/√2. Relative phase is 45° (0.7854 rad).',
    matrixFormula: 'T = \\begin{pmatrix} 1 & 0 \\\\ 0 & e^{i\\pi/4} \\end{pmatrix}',
    circuit: {
      id: 'circ-qrl-006',
      name: 'QRL-006 T Gate Non-Clifford',
      description: 'H followed by T gate',
      numQubits: 1,
      timeSteps: 4,
      gates: [
        { id: 'g1', type: 'H', step: 0, targetQubit: 0 },
        { id: 'g2', type: 'T', step: 1, targetQubit: 0 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-007',
    code: 'QRL-007',
    name: 'Continuous Rotation RX(π/3)',
    category: 'Phase & Rotation',
    numQubits: 1,
    circuitDepth: 1,
    gateCount: 1,
    cnotCount: 0,
    referenceFidelity: 0.9997,
    verifiedBaseline: true,
    description: 'Rotates the statevector around the X-axis by θ = π/3 (60°), producing non-trivial complex amplitudes.',
    learningObjectives: [
      'Calculate theoretical probability P(|0⟩) = cos²(θ/2) and P(|1⟩) = sin²(θ/2).',
      'For θ = π/3: cos²(π/6) = 3/4 = 0.75, sin²(π/6) = 1/4 = 0.25.',
    ],
    theoreticalBehavior: 'P(|0⟩) = 0.75, P(|1⟩) = 0.25.',
    matrixFormula: 'R_X(\\theta) = \\begin{pmatrix} \\cos(\\theta/2) & -i\\sin(\\theta/2) \\\\ -i\\sin(\\theta/2) & \\cos(\\theta/2) \\end{pmatrix}',
    circuit: {
      id: 'circ-qrl-007',
      name: 'QRL-007 Continuous RX(π/3)',
      description: 'RX with angle pi/3',
      numQubits: 1,
      timeSteps: 4,
      gates: [
        { id: 'g1', type: 'RX', step: 0, targetQubit: 0, parameter: Math.PI / 3 },
        { id: 'g2', type: 'M', step: 1, targetQubit: 0 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-008',
    code: 'QRL-008',
    name: 'Continuous Rotation RY(π/2) Balanced Superposition',
    category: 'Phase & Rotation',
    numQubits: 1,
    circuitDepth: 1,
    gateCount: 1,
    cnotCount: 0,
    referenceFidelity: 0.9999,
    verifiedBaseline: true,
    description: 'Rotates around the Y axis by π/2, generating a real-valued equal superposition state without complex phases.',
    learningObjectives: [
      'Examine real-valued superposition: RY(π/2)|0⟩ = (|0⟩ + |1⟩)/√2.',
      'Contrast with Hadamard transformation.',
    ],
    theoreticalBehavior: 'P(|0⟩) = 0.5, P(|1⟩) = 0.5. Phase angle is identically 0° for both basis states.',
    matrixFormula: 'R_Y(\\theta) = \\begin{pmatrix} \\cos(\\theta/2) & -\\sin(\\theta/2) \\\\ \\sin(\\theta/2) & \\cos(\\theta/2) \\end{pmatrix}',
    circuit: {
      id: 'circ-qrl-008',
      name: 'QRL-008 RY(π/2) Balanced Superposition',
      description: 'RY gate with angle pi/2',
      numQubits: 1,
      timeSteps: 4,
      gates: [
        { id: 'g1', type: 'RY', step: 0, targetQubit: 0, parameter: Math.PI / 2 },
        { id: 'g2', type: 'M', step: 1, targetQubit: 0 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-009',
    code: 'QRL-009',
    name: 'Continuous Rotation RZ(π) Phase Evolution',
    category: 'Phase & Rotation',
    numQubits: 1,
    circuitDepth: 3,
    gateCount: 3,
    cnotCount: 0,
    referenceFidelity: 0.9996,
    verifiedBaseline: true,
    description: 'Applies full longitudinal rotation around the Z axis inside an interferometric Ramsey-style sequence.',
    learningObjectives: [
      'Track state rotation in the equatorial plane of the Bloch sphere.',
      'Measure state evolution via Ramsey interferometry (H - RZ(θ) - H).',
    ],
    theoreticalBehavior: 'H - RZ(π) - H produces state |1⟩ with probability 1.0.',
    matrixFormula: 'R_Z(\\theta) = \\begin{pmatrix} e^{-i\\theta/2} & 0 \\\\ 0 & e^{i\\theta/2} \\end{pmatrix}',
    circuit: {
      id: 'circ-qrl-009',
      name: 'QRL-009 RZ(π) Ramsey Sequence',
      description: 'H - RZ(pi) - H interferometry',
      numQubits: 1,
      timeSteps: 5,
      gates: [
        { id: 'g1', type: 'H', step: 0, targetQubit: 0 },
        { id: 'g2', type: 'RZ', step: 1, targetQubit: 0, parameter: Math.PI },
        { id: 'g3', type: 'H', step: 2, targetQubit: 0 },
        { id: 'g4', type: 'M', step: 3, targetQubit: 0 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-010',
    code: 'QRL-010',
    name: 'Bell State |Φ+⟩ Generation (EPR Pair)',
    category: 'Bell States',
    numQubits: 2,
    circuitDepth: 2,
    gateCount: 2,
    cnotCount: 1,
    referenceFidelity: 0.9992,
    verifiedBaseline: true,
    description: 'Canonical maximally entangled two-qubit Bell pair: |Φ+⟩ = (|00⟩ + |11⟩)/√2. Demonstrates quantum non-locality.',
    learningObjectives: [
      'Create entanglement using a Hadamard gate on qubit 0 followed by CNOT(0, 1).',
      'Confirm zero probability for anti-correlated states |01⟩ and |10⟩.',
      'Inspect reduced density matrix purity = 0.5 (maximally mixed single qubit subsystems).',
    ],
    theoreticalBehavior: 'P(|00⟩) = 0.5, P(|11⟩) = 0.5, P(|01⟩) = 0, P(|10⟩) = 0. Bloch vectors for individual qubits collapse to center (0, 0, 0).',
    matrixFormula: '|\\Phi^+\\rangle = \\frac{|00\\rangle + |11\\rangle}{\\sqrt{2}}',
    circuit: {
      id: 'circ-qrl-010',
      name: 'QRL-010 Bell State |Φ+⟩',
      description: 'H on q0, CNOT(0, 1)',
      numQubits: 2,
      timeSteps: 4,
      gates: [
        { id: 'g1', type: 'H', step: 0, targetQubit: 0 },
        { id: 'g2', type: 'CX', step: 1, targetQubit: 1, controlQubits: [0] },
        { id: 'g3', type: 'M', step: 2, targetQubit: 0 },
        { id: 'g4', type: 'M', step: 2, targetQubit: 1 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-011',
    code: 'QRL-011',
    name: 'Bell State |Φ-⟩ Generation',
    category: 'Bell States',
    numQubits: 2,
    circuitDepth: 3,
    gateCount: 3,
    cnotCount: 1,
    referenceFidelity: 0.9989,
    verifiedBaseline: true,
    description: 'Second Bell basis state: |Φ-⟩ = (|00⟩ - |11⟩)/√2 created by adding a Pauli-Z phase flip before CNOT.',
    learningObjectives: [
      'Verify how relative phase changes state parity without affecting joint basis correlations.',
      'Correlate measurements in Z-basis versus X-basis.',
    ],
    theoreticalBehavior: 'P(|00⟩) = 0.5, P(|11⟩) = 0.5 with π phase offset between amplitudes.',
    matrixFormula: '|\\Phi^-\\rangle = \\frac{|00\\rangle - |11\\rangle}{\\sqrt{2}}',
    circuit: {
      id: 'circ-qrl-011',
      name: 'QRL-011 Bell State |Φ-⟩',
      description: 'X on q0, H on q0, CNOT(0, 1)',
      numQubits: 2,
      timeSteps: 5,
      gates: [
        { id: 'g1', type: 'X', step: 0, targetQubit: 0 },
        { id: 'g2', type: 'H', step: 1, targetQubit: 0 },
        { id: 'g3', type: 'CX', step: 2, targetQubit: 1, controlQubits: [0] },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-012',
    code: 'QRL-012',
    name: 'Bell State |Ψ+⟩ Generation',
    category: 'Bell States',
    numQubits: 2,
    circuitDepth: 3,
    gateCount: 3,
    cnotCount: 1,
    referenceFidelity: 0.9991,
    verifiedBaseline: true,
    description: 'Anti-correlated Bell state: |Ψ+⟩ = (|01⟩ + |10⟩)/√2, where qubits always measure opposite values.',
    learningObjectives: [
      'Observe perfect anti-correlation in computational basis.',
      'Verify P(|01⟩) = 0.5 and P(|10⟩) = 0.5.',
    ],
    theoreticalBehavior: 'P(|01⟩) = 0.5, P(|10⟩) = 0.5; P(|00⟩) = 0, P(|11⟩) = 0.',
    matrixFormula: '|\\Psi^+\\rangle = \\frac{|01\\rangle + |10\\rangle}{\\sqrt{2}}',
    circuit: {
      id: 'circ-qrl-012',
      name: 'QRL-012 Bell State |Ψ+⟩',
      description: 'X on q1, H on q0, CNOT(0, 1)',
      numQubits: 2,
      timeSteps: 5,
      gates: [
        { id: 'g1', type: 'X', step: 0, targetQubit: 1 },
        { id: 'g2', type: 'H', step: 1, targetQubit: 0 },
        { id: 'g3', type: 'CX', step: 2, targetQubit: 1, controlQubits: [0] },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-013',
    code: 'QRL-013',
    name: 'Bell State |Ψ-⟩ Generation (Singlet State)',
    category: 'Bell States',
    numQubits: 2,
    circuitDepth: 4,
    gateCount: 4,
    cnotCount: 1,
    referenceFidelity: 0.9987,
    verifiedBaseline: true,
    description: 'The singlet state: |Ψ-⟩ = (|01⟩ - |10⟩)/√2. Invariant under any simultaneous rotation of both qubits.',
    learningObjectives: [
      'Analyze rotational invariance: total angular momentum S = 0.',
      'Key resource for quantum teleportation and Ekert91 quantum key distribution.',
    ],
    theoreticalBehavior: 'Anti-correlated states |01⟩ and |10⟩ with negative relative phase.',
    matrixFormula: '|\\Psi^-\\rangle = \\frac{|01\\rangle - |10\\rangle}{\\sqrt{2}}',
    circuit: {
      id: 'circ-qrl-013',
      name: 'QRL-013 Singlet State |Ψ-⟩',
      description: 'X on q0, X on q1, H on q0, CNOT(0, 1)',
      numQubits: 2,
      timeSteps: 5,
      gates: [
        { id: 'g1', type: 'X', step: 0, targetQubit: 0 },
        { id: 'g2', type: 'X', step: 0, targetQubit: 1 },
        { id: 'g3', type: 'H', step: 1, targetQubit: 0 },
        { id: 'g4', type: 'CX', step: 2, targetQubit: 1, controlQubits: [0] },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-014',
    code: 'QRL-014',
    name: '3-Qubit GHZ State Entanglement',
    category: 'GHZ States',
    numQubits: 3,
    circuitDepth: 3,
    gateCount: 3,
    cnotCount: 2,
    referenceFidelity: 0.9982,
    verifiedBaseline: true,
    description: 'Greenberger-Horne-Zeilinger state: (|000⟩ + |111⟩)/√2. Maximally entangled multipartite quantum state.',
    learningObjectives: [
      'Observe genuine tripartite entanglement.',
      'Verify that tracing out any single qubit completely destroys bipartite entanglement between the remaining pair.',
      'Examine macroscopic quantum superpositions (Schrödinger cat states).',
    ],
    theoreticalBehavior: 'P(|000⟩) = 0.5, P(|111⟩) = 0.5; all other 6 basis states measure 0.0.',
    matrixFormula: '|GHZ\\rangle = \\frac{|000\\rangle + |111\\rangle}{\\sqrt{2}}',
    circuit: {
      id: 'circ-qrl-014',
      name: 'QRL-014 3-Qubit GHZ State',
      description: 'H on q0, CNOT(0,1), CNOT(1,2)',
      numQubits: 3,
      timeSteps: 5,
      gates: [
        { id: 'g1', type: 'H', step: 0, targetQubit: 0 },
        { id: 'g2', type: 'CX', step: 1, targetQubit: 1, controlQubits: [0] },
        { id: 'g3', type: 'CX', step: 2, targetQubit: 2, controlQubits: [1] },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-015',
    code: 'QRL-015',
    name: '3-Qubit W State Approximation',
    category: 'GHZ States',
    numQubits: 3,
    circuitDepth: 4,
    gateCount: 5,
    cnotCount: 2,
    referenceFidelity: 0.9975,
    verifiedBaseline: true,
    description: 'Robust tripartite entanglement: (|001⟩ + |010⟩ + |100⟩)/√3. Robust against the loss of a single qubit.',
    learningObjectives: [
      'Compare W state robustness against GHZ state vulnerability to qubit loss.',
      'Observe equal third-probabilities P(|001⟩) = P(|010⟩) = P(|100⟩) ≈ 0.333.',
    ],
    theoreticalBehavior: 'P(|001⟩) = P(|010⟩) = P(|100⟩) = 1/3 ≈ 0.3333.',
    matrixFormula: '|W\\rangle = \\frac{|100\\rangle + |010\\rangle + |001\\rangle}{\\sqrt{3}}',
    circuit: {
      id: 'circ-qrl-015',
      name: 'QRL-015 3-Qubit W State',
      description: 'RY rotations and controlled operations',
      numQubits: 3,
      timeSteps: 6,
      gates: [
        { id: 'g1', type: 'RY', step: 0, targetQubit: 0, parameter: 1.9106 }, // 2*arccos(1/sqrt(3))
        { id: 'g2', type: 'CX', step: 1, targetQubit: 1, controlQubits: [0] },
        { id: 'g3', type: 'RY', step: 2, targetQubit: 0, parameter: -Math.PI / 4 },
        { id: 'g4', type: 'CX', step: 3, targetQubit: 2, controlQubits: [0] },
        { id: 'g5', type: 'X', step: 4, targetQubit: 0 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-016',
    code: 'QRL-016',
    name: '2-Qubit SWAP Gate Verification',
    category: 'Controlled & Entanglement',
    numQubits: 2,
    circuitDepth: 3,
    gateCount: 2,
    cnotCount: 0,
    referenceFidelity: 0.9995,
    verifiedBaseline: true,
    description: 'Exchanges the state of qubit 0 with qubit 1. Demonstrates state transfer across physical coupling topologies.',
    learningObjectives: [
      'Prepare |10⟩ (X on q0) and execute SWAP.',
      'Verify target qubit q1 receives |1⟩, resulting in deterministic state |01⟩.',
      'Understand decomposition into 3 alternating CNOT gates.',
    ],
    theoreticalBehavior: 'Initial state |10⟩ maps to |01⟩ with probability 1.0.',
    matrixFormula: '\\text{SWAP} = \\begin{pmatrix} 1 & 0 & 0 & 0 \\\\ 0 & 0 & 1 & 0 \\\\ 0 & 1 & 0 & 0 \\\\ 0 & 0 & 0 & 1 \\end{pmatrix}',
    circuit: {
      id: 'circ-qrl-016',
      name: 'QRL-016 SWAP Gate Verification',
      description: 'X on q0, SWAP(q0, q1)',
      numQubits: 2,
      timeSteps: 4,
      gates: [
        { id: 'g1', type: 'X', step: 0, targetQubit: 0 },
        { id: 'g2', type: 'SWAP', step: 1, targetQubit: 0, secondTarget: 1 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-017',
    code: 'QRL-017',
    name: 'Controlled-Z (CZ) Symmetric Phase Gate',
    category: 'Controlled & Entanglement',
    numQubits: 2,
    circuitDepth: 3,
    gateCount: 3,
    cnotCount: 0,
    referenceFidelity: 0.9992,
    verifiedBaseline: true,
    description: 'Symmetric entangling gate that imparts a -1 phase factor exclusively to the joint state |11⟩.',
    learningObjectives: [
      'Observe symmetry: CZ is identical regardless of which qubit is designated control or target.',
      'Verify equivalence to H on target, CNOT, H on target.',
    ],
    theoreticalBehavior: 'Applies phase flip to |11⟩. In H-H superposition, creates cluster state (|00⟩+|01⟩+|10⟩-|11⟩)/2.',
    matrixFormula: '\\text{CZ} = \\text{diag}(1, 1, 1, -1)',
    circuit: {
      id: 'circ-qrl-017',
      name: 'QRL-017 Controlled-Z Gate',
      description: 'H on q0, H on q1, CZ(0, 1)',
      numQubits: 2,
      timeSteps: 4,
      gates: [
        { id: 'g1', type: 'H', step: 0, targetQubit: 0 },
        { id: 'g2', type: 'H', step: 0, targetQubit: 1 },
        { id: 'g3', type: 'CZ', step: 1, targetQubit: 1, controlQubits: [0] },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-018',
    code: 'QRL-018',
    name: "Deutsch's Algorithm (Balanced Oracle)",
    category: 'Quantum Algorithms',
    numQubits: 2,
    circuitDepth: 4,
    gateCount: 5,
    cnotCount: 1,
    referenceFidelity: 0.9988,
    verifiedBaseline: true,
    description: 'First historical demonstration of quantum speedup: determines whether f(x) is constant or balanced in a single query.',
    learningObjectives: [
      'Understand quantum phase kickback using ancilla qubit initialized to |-⟩.',
      'Demonstrate constructive interference on |1⟩ indicating balanced function.',
      'Solve in 1 query what requires 2 queries classically.',
    ],
    theoreticalBehavior: 'Balanced oracle returns qubit 0 in state |1⟩ with 100% certainty.',
    matrixFormula: 'U_f: |x\\rangle|y\\rangle \\to |x\\rangle|y \\oplus f(x)\\rangle',
    circuit: {
      id: 'circ-qrl-018',
      name: "QRL-018 Deutsch's Algorithm",
      description: 'Balanced oracle evaluation',
      numQubits: 2,
      timeSteps: 6,
      gates: [
        { id: 'g1', type: 'X', step: 0, targetQubit: 1 },
        { id: 'g2', type: 'H', step: 1, targetQubit: 0 },
        { id: 'g3', type: 'H', step: 1, targetQubit: 1 },
        { id: 'g4', type: 'CX', step: 2, targetQubit: 1, controlQubits: [0] },
        { id: 'g5', type: 'H', step: 3, targetQubit: 0 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-019',
    code: 'QRL-019',
    name: 'Deutsch-Jozsa Algorithm (Constant Oracle)',
    category: 'Quantum Algorithms',
    numQubits: 3,
    circuitDepth: 4,
    gateCount: 6,
    cnotCount: 0,
    referenceFidelity: 0.9984,
    verifiedBaseline: true,
    description: 'Generalization of Deutsch algorithm: verifies constant function for 2 input qubits in a single query.',
    learningObjectives: [
      'Scale phase kickback to multi-qubit input registers.',
      'Confirm input register measures all zeros (|00⟩) for a constant oracle.',
    ],
    theoreticalBehavior: 'Measurement of input register q0, q1 yields |00⟩ with probability 1.0.',
    matrixFormula: 'f(x) = c \\implies |00\\dots0\\rangle \\text{ measured}',
    circuit: {
      id: 'circ-qrl-019',
      name: 'QRL-019 Deutsch-Jozsa Constant Oracle',
      description: '2 input qubits + 1 ancilla',
      numQubits: 3,
      timeSteps: 6,
      gates: [
        { id: 'g1', type: 'X', step: 0, targetQubit: 2 },
        { id: 'g2', type: 'H', step: 1, targetQubit: 0 },
        { id: 'g3', type: 'H', step: 1, targetQubit: 1 },
        { id: 'g4', type: 'H', step: 1, targetQubit: 2 },
        { id: 'g5', type: 'H', step: 2, targetQubit: 0 },
        { id: 'g6', type: 'H', step: 2, targetQubit: 1 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-020',
    code: 'QRL-020',
    name: 'Bernstein-Vazirani Secret Bitstring Finder (s="11")',
    category: 'Quantum Algorithms',
    numQubits: 3,
    circuitDepth: 5,
    gateCount: 7,
    cnotCount: 2,
    referenceFidelity: 0.9981,
    verifiedBaseline: true,
    description: 'Finds hidden n-bit string s where oracle computes f(x) = s · x (mod 2) in 1 query instead of n queries.',
    learningObjectives: [
      'Implement oracle for hidden string s = 11.',
      'Verify register measurement immediately produces the exact bitstring "11".',
    ],
    theoreticalBehavior: 'Qubits 0 and 1 measure "11" with 100% theoretical probability.',
    matrixFormula: 'f(x) = s \\cdot x \\pmod 2 \\implies |s\\rangle \\text{ directly observed}',
    circuit: {
      id: 'circ-qrl-020',
      name: 'QRL-020 Bernstein-Vazirani s=11',
      description: 'Recovers hidden string 11 in one query',
      numQubits: 3,
      timeSteps: 7,
      gates: [
        { id: 'g1', type: 'X', step: 0, targetQubit: 2 },
        { id: 'g2', type: 'H', step: 1, targetQubit: 0 },
        { id: 'g3', type: 'H', step: 1, targetQubit: 1 },
        { id: 'g4', type: 'H', step: 1, targetQubit: 2 },
        { id: 'g5', type: 'CX', step: 2, targetQubit: 2, controlQubits: [0] },
        { id: 'g6', type: 'CX', step: 3, targetQubit: 2, controlQubits: [1] },
        { id: 'g7', type: 'H', step: 4, targetQubit: 0 },
        { id: 'g8', type: 'H', step: 4, targetQubit: 1 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-021',
    code: 'QRL-021',
    name: "Grover's 2-Qubit Search Algorithm (Target |11⟩)",
    category: 'Quantum Algorithms',
    numQubits: 2,
    circuitDepth: 6,
    gateCount: 7,
    cnotCount: 0,
    referenceFidelity: 0.9985,
    verifiedBaseline: true,
    description: "Quadratic speedup search for unmarked database: amplifies the probability amplitude of target state |11⟩ to 100% in 1 iteration.",
    learningObjectives: [
      'Construct Grover oracle (phase inversion of target state via CZ).',
      'Construct Grover diffusion operator (inversion about the mean).',
      'Observe constructive interference concentrating 100% probability onto |11⟩.',
    ],
    theoreticalBehavior: 'P(|11⟩) = 1.0, P(|00⟩)=0, P(|01⟩)=0, P(|10⟩)=0.',
    matrixFormula: 'G = (2|s\\rangle\\langle s| - I) U_\\omega',
    circuit: {
      id: 'circ-qrl-021',
      name: "QRL-021 Grover Search (|11⟩)",
      description: 'Oracle and diffusion operator for 2 qubits',
      numQubits: 2,
      timeSteps: 7,
      gates: [
        { id: 'g1', type: 'H', step: 0, targetQubit: 0 },
        { id: 'g2', type: 'H', step: 0, targetQubit: 1 },
        // Oracle for |11>
        { id: 'g3', type: 'CZ', step: 1, targetQubit: 1, controlQubits: [0] },
        // Diffusion operator
        { id: 'g4', type: 'H', step: 2, targetQubit: 0 },
        { id: 'g5', type: 'H', step: 2, targetQubit: 1 },
        { id: 'g6', type: 'Z', step: 3, targetQubit: 0 },
        { id: 'g7', type: 'Z', step: 3, targetQubit: 1 },
        { id: 'g8', type: 'CZ', step: 4, targetQubit: 1, controlQubits: [0] },
        { id: 'g9', type: 'H', step: 5, targetQubit: 0 },
        { id: 'g10', type: 'H', step: 5, targetQubit: 1 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-022',
    code: 'QRL-022',
    name: '3-Qubit Quantum Fourier Transform (QFT)',
    category: 'Quantum Algorithms',
    numQubits: 3,
    circuitDepth: 7,
    gateCount: 7,
    cnotCount: 0,
    referenceFidelity: 0.9976,
    verifiedBaseline: true,
    description: 'Quantum analog of discrete Fourier transform: transforms computational basis into frequency basis with exponential speedup.',
    learningObjectives: [
      'Understand conditional phase rotations between qubits.',
      'Prepare input state |100⟩ (q0=1) and analyze resulting continuous Fourier phases.',
      'Core primitive for Shor factoring and Quantum Phase Estimation.',
    ],
    theoreticalBehavior: 'Creates uniform probability distribution across all 8 states with linear phase increments.',
    matrixFormula: '\\text{QFT}|j\\rangle = \\frac{1}{\\sqrt{2^n}}\\sum_{k=0}^{2^n-1} e^{2\\pi i j k / 2^n} |k\\rangle',
    circuit: {
      id: 'circ-qrl-022',
      name: 'QRL-022 3-Qubit QFT',
      description: 'Hadamard and controlled-phase rotations',
      numQubits: 3,
      timeSteps: 8,
      gates: [
        { id: 'g0', type: 'X', step: 0, targetQubit: 0 }, // Input |100>
        { id: 'g1', type: 'H', step: 1, targetQubit: 0 },
        { id: 'g2', type: 'Phase', step: 2, targetQubit: 0, parameter: Math.PI / 2 },
        { id: 'g3', type: 'H', step: 3, targetQubit: 1 },
        { id: 'g4', type: 'Phase', step: 4, targetQubit: 1, parameter: Math.PI / 2 },
        { id: 'g5', type: 'H', step: 5, targetQubit: 2 },
        { id: 'g6', type: 'SWAP', step: 6, targetQubit: 0, secondTarget: 2 },
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
  {
    id: 'exp-023',
    code: 'QRL-023',
    name: 'Variational Quantum Classifier (Ansatz Layer & Proxy Optimization)',
    category: 'Quantum Machine Learning',
    numQubits: 2,
    circuitDepth: 4,
    gateCount: 5,
    cnotCount: 1,
    referenceFidelity: 0.9983,
    verifiedBaseline: true,
    description: 'Hardware-efficient parameterized ansatz with angle feature encoding and trainable variational parameter layers. Demonstrates variational parameter optimization on simulated statevectors (proxy loss model, not a physical hardware-trained QML classifier).',
    learningObjectives: [
      'Explore classical-quantum hybrid workflow with parameterized quantum circuits (PQCs).',
      'Understand parameter shift rules and empirical proxy-loss optimization.',
      'Observe decision boundary separation in two-qubit Hilbert space without claiming physical hardware QPU execution.',
    ],
    theoreticalBehavior: 'Parameterized output probabilities sensitive to continuous rotation parameter θ.',
    matrixFormula: 'U(\\vec{\\theta}) = \\prod_{l=1}^L W_l U_{\\text{ent}}',
    circuit: {
      id: 'circ-qrl-023',
      name: 'QRL-023 Variational Quantum Classifier',
      description: 'Angle encoding + trainable RY layers + CNOT entanglement',
      numQubits: 2,
      timeSteps: 6,
      gates: [
        // Feature encoding layer
        { id: 'g1', type: 'RY', step: 0, targetQubit: 0, parameter: 0.7854 }, // x0 = pi/4
        { id: 'g2', type: 'RY', step: 0, targetQubit: 1, parameter: 1.5708 }, // x1 = pi/2
        // Entangling layer
        { id: 'g3', type: 'CX', step: 1, targetQubit: 1, controlQubits: [0] },
        // Trainable variational layer
        { id: 'g4', type: 'RY', step: 2, targetQubit: 0, parameter: 2.3562 }, // theta0
        { id: 'g5', type: 'RZ', step: 3, targetQubit: 1, parameter: 1.0472 }, // theta1
      ],
      createdAt: '2026-03-01T00:00:00Z',
      updatedAt: '2026-03-01T00:00:00Z',
    },
    qiskitCode: '',
    pennylaneCode: '',
  },
];

// Pre-fill Qiskit and PennyLane code strings
VERIFIED_EXPERIMENTS.forEach((exp) => {
  exp.qiskitCode = exportToQiskit(exp.circuit);
  exp.pennylaneCode = exportToPennyLane(exp.circuit);
});
